//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarLint.VisualStudio.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarLint.VisualStudio.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Notifications] Failed to read disabled notification config from disk. Error: {0}.
        /// </summary>
        internal static string DisabledNotificationReadError {
            get {
                return ResourceManager.GetString("DisabledNotificationReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Notifications] Failed to save disabled notification config to disk. Error: {0}.
        /// </summary>
        internal static string DisabledNotificationSaveError {
            get {
                return ResourceManager.GetString("DisabledNotificationSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Notifications] Couldn&apos;t load disabled notification config. Notification will be shown..
        /// </summary>
        internal static string DisabledNotificationsFailedToLoad {
            get {
                return ResourceManager.GetString("DisabledNotificationsFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error handling file change notification: {0}.
        /// </summary>
        internal static string FileMonitor_ErrorHandlingFileChange {
            get {
                return ResourceManager.GetString("FileMonitor_ErrorHandlingFileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File changed: {0}. Change type: {1}.
        /// </summary>
        internal static string FileMonitor_FileChanged {
            get {
                return ResourceManager.GetString("FileMonitor_FileChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created directory: {0}.
        /// </summary>
        internal static string FileMonitory_CreatedDirectory {
            get {
                return ResourceManager.GetString("FileMonitory_CreatedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default settings will be used.
        /// </summary>
        internal static string Settings_UsingDefaultSettings {
            get {
                return ResourceManager.GetString("Settings_UsingDefaultSettings", resourceCulture);
            }
        }
    }
}
