env:
  ARTIFACTORY_URL: VAULT[development/kv/data/repox data.url]
  ARTIFACTORY_PRIVATE_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader
  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  ARTIFACTORY_DEPLOY_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer
  ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
  ARTIFACTORY_DEPLOY_REPO: sonarsource-public-qa
  ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  # Use bash (instead of sh on linux or cmd.exe on windows)
  CIRRUS_SHELL: powershell

ec2_instance_definition: &INSTANCE_DEFINITION
  region: eu-central-1
  type: t3a.xlarge
  image: base-windows-dotnet-v*
  platform: windows

build_dotnet_task:
  ec2_instance:
    <<: *INSTANCE_DEFINITION
  env:
    ARTIFACTORY_USER: ${ARTIFACTORY_PRIVATE_USERNAME}
    ARTIFACTORY_PASSWORD: ${ARTIFACTORY_PRIVATE_PASSWORD}
    SOLUTION_PATH: .\sonarlint-visualstudio\SonarLint.VisualStudio.Integration.sln
    CIRRUS_WORKING_DIR: C:\sonar-ci
    APPDATA: C:\sonar-ci\AppData\Roaming
    LOCALAPPDATA: C:\sonar-ci\AppData\Local
    USERPROFILE: C:\sonar-ci
    MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\msbuild.exe
    PATH: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin:${PATH}

  create_directories_script:
    - New-Item -ItemType Directory -Path $env:APPDATA -Force
    - New-Item -ItemType Directory -Path $env:LOCALAPPDATA -Force

  download_jar_dependencies_script:
    - msbuild.exe build\DownloadDependencies /p:VsVersion=17.0 /p:VsTargetVersion=2022

  dotnet_restore_script:
    # Restore the .NET projects using Repox as source feed
    - dotnet.exe restore "${SOLUTION_PATH}" --locked-mode

  build_solution_script:
    - msbuild.exe "${SOLUTION_PATH}" /p:VsVersion=17.0 /p:VsTargetVersion=2022 /p:AssemblyOriginatorKeyFile=${SONARSOURCE_SNK_PATH} /p:DeployExtension=false /p:Sha1=${CI_COMMIT_SHA} /p:BuildNumber=${CIRRUS_BUILD_ID}
