/*
 * SonarLint for Visual Studio
 * Copyright (C) 2016-2020 SonarSource SA
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

using Microsoft.VisualStudio.Text;
using SonarLint.VisualStudio.Core.Analysis;

namespace SonarLint.VisualStudio.Integration.Vsix
{
    /// <summary>
    /// Data class to associate an issue generated by the daemon
    /// with a span in an ITextBuffer
    /// </summary>
    /// <remarks>
    /// See the README.md in this folder for more information
    /// </remarks>
    internal class IssueMarker
    {
        public IAnalysisIssue Issue { get; }
        public SnapshotSpan? Span { get; }

        public IssueMarker(IAnalysisIssue issue, SnapshotSpan? span)
        {
            this.Issue = issue;
            this.Span = span;
        }

        public IssueMarker Clone()
        {
            return new IssueMarker(Issue, Span);
        }

        public IssueMarker CloneAndTranslateTo(ITextSnapshot newSnapshot)
        {
            var newSpan = Span?.TranslateTo(newSnapshot, SpanTrackingMode.EdgeExclusive);

            // If the span length changed, the marker is no longer valid
            if (newSpan?.Length != Span?.Length)
            {
                return null;
            }
            return new IssueMarker(Issue, newSpan);
        }
    }
}
