//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarLint.VisualStudio.IssueVisualization.Security.Taint {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaintResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaintResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintResources", typeof(TaintResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Taint] Failed to synchronize taint vulnerabilities with the connected server: {0}..
        /// </summary>
        internal static string Synchronizer_Failure {
            get {
                return ResourceManager.GetString("Synchronizer_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Taint] Unable to fetch taint vulnerabilities: not in connected mode..
        /// </summary>
        internal static string Synchronizer_NotInConnectedMode {
            get {
                return ResourceManager.GetString("Synchronizer_NotInConnectedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Taint] Fetched {0} taint vulnerabilities..
        /// </summary>
        internal static string Synchronizer_NumberOfServerIssues {
            get {
                return ResourceManager.GetString("Synchronizer_NumberOfServerIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Taint] Unable to fetch taint vulnerabilities: a connection to the server is not yet established..
        /// </summary>
        internal static string Synchronizer_ServerNotConnected {
            get {
                return ResourceManager.GetString("Synchronizer_ServerNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Taint] Displaying taint vulnerabilities in the IDE requires SonarQube v8.6 or later, or SonarCloud. Connected SonarQube version: v{0}
        ///    Visit https://docs.sonarsource.com/sonarlint/visual-studio/using-sonarlint/taint-vulnerabilities/ to find out more about this and other SonarLint features..
        /// </summary>
        internal static string Synchronizer_UnsupportedSQVersion {
            get {
                return ResourceManager.GetString("Synchronizer_UnsupportedSQVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Taint] Finished initializing taint issues synchronization package..
        /// </summary>
        internal static string SyncPackage_Initialized {
            get {
                return ResourceManager.GetString("SyncPackage_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Taint] Initializing taint issues synchronization package....
        /// </summary>
        internal static string SyncPackage_Initializing {
            get {
                return ResourceManager.GetString("SyncPackage_Initializing", resourceCulture);
            }
        }
    }
}
