//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarLint.VisualStudio.IssueVisualization.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarLint.VisualStudio.IssueVisualization.Security.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity impact:.
        /// </summary>
        public static string DependencyRiskImpactSeverityTooltip {
            get {
                return ResourceManager.GetString("DependencyRiskImpactSeverityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution findings.
        /// </summary>
        public static string DependencyRisksGroupTitle {
            get {
                return ResourceManager.GetString("DependencyRisksGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohibited License.
        /// </summary>
        public static string DependencyRiskType_ProhibitedLicense {
            get {
                return ResourceManager.GetString("DependencyRiskType_ProhibitedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error displaying tool window. Window id: {0}. Error: {1}.
        /// </summary>
        public static string ERR_ShowToolWindow_Exception {
            get {
                return ResourceManager.GetString("ERR_ShowToolWindow_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished initializing security package..
        /// </summary>
        public static string FinishedPackageInitialization {
            get {
                return ResourceManager.GetString("FinishedPackageInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hotspots not yet present on the server need to be fixed locally..
        /// </summary>
        public static string HotspotControl_LocalHotspotStatusTooltip {
            get {
                return ResourceManager.GetString("HotspotControl_LocalHotspotStatusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string HotspotsControl_CodeColumnHeader {
            get {
                return ResourceManager.GetString("HotspotsControl_CodeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col.
        /// </summary>
        public static string HotspotsControl_ColColumnHeader {
            get {
                return ResourceManager.GetString("HotspotsControl_ColColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Document.
        /// </summary>
        public static string HotspotsControl_CurrentDocumentFilter {
            get {
                return ResourceManager.GetString("HotspotsControl_CurrentDocumentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string HotspotsControl_DescriptionColumnHeader {
            get {
                return ResourceManager.GetString("HotspotsControl_DescriptionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string HotspotsControl_FileColumnHeader {
            get {
                return ResourceManager.GetString("HotspotsControl_FileColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string HotspotsControl_LineColumnHeader {
            get {
                return ResourceManager.GetString("HotspotsControl_LineColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot navigate to location. The source code is different from the analyzed version..
        /// </summary>
        public static string HotspotsControl_NavigationErrorTooltip {
            get {
                return ResourceManager.GetString("HotspotsControl_NavigationErrorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use double-click or Enter to navigate to the security hotspot..
        /// </summary>
        public static string HotspotsControl_NavigationTooltip {
            get {
                return ResourceManager.GetString("HotspotsControl_NavigationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Hotspot does not exist on the server..
        /// </summary>
        public static string HotspotsControl_NotOnServerTooltip {
            get {
                return ResourceManager.GetString("HotspotsControl_NotOnServerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Documents.
        /// </summary>
        public static string HotspotsControl_OpenDocumentsFilter {
            get {
                return ResourceManager.GetString("HotspotsControl_OpenDocumentsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string HotspotsControl_PriorityColumnHeader {
            get {
                return ResourceManager.GetString("HotspotsControl_PriorityColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Security Hotspot.
        /// </summary>
        public static string HotspotsControl_ReviewHotspotTooltip {
            get {
                return ResourceManager.GetString("HotspotsControl_ReviewHotspotTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server status.
        /// </summary>
        public static string HotspotsControl_ServerStatusColumnHeader {
            get {
                return ResourceManager.GetString("HotspotsControl_ServerStatusColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Hotspot exists on SonarQube Cloud..
        /// </summary>
        public static string HotspotsControl_SonarCloudTooltip {
            get {
                return ResourceManager.GetString("HotspotsControl_SonarCloudTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Hotspot exists on SonarQube Server..
        /// </summary>
        public static string HotspotsControl_SonarQubeTooltip {
            get {
                return ResourceManager.GetString("HotspotsControl_SonarQubeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string HotspotsControl_StatusColumnHeader {
            get {
                return ResourceManager.GetString("HotspotsControl_StatusColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in SonarQube Cloud.
        /// </summary>
        public static string HotspotsControl_ViewInSonarQubeCloud {
            get {
                return ResourceManager.GetString("HotspotsControl_ViewInSonarQubeCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in SonarQube Server.
        /// </summary>
        public static string HotspotsControl_ViewInSonarQubeServer {
            get {
                return ResourceManager.GetString("HotspotsControl_ViewInSonarQubeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Review.
        /// </summary>
        public static string HotspotStatus_ToReview {
            get {
                return ResourceManager.GetString("HotspotStatus_ToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube Security Hotspots.
        /// </summary>
        public static string HotspotsToolWindowCaption {
            get {
                return ResourceManager.GetString("HotspotsToolWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issue.
        /// </summary>
        public static string IssueText {
            get {
                return ResourceManager.GetString("IssueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that your solution is bound to a SonarQube project that contains dependency risks..
        /// </summary>
        public static string NoDependencyRiskFoundText {
            get {
                return ResourceManager.GetString("NoDependencyRiskFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dependency Risks were found..
        /// </summary>
        public static string NoDependencyRiskFoundTitle {
            get {
                return ResourceManager.GetString("NoDependencyRiskFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube Dependency Risks.
        /// </summary>
        public static string ReportViewToolWindowCaption {
            get {
                return ResourceManager.GetString("ReportViewToolWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reviewing hotspot: {0}..
        /// </summary>
        public static string ReviewHotspotService_AnErrorOccurred {
            get {
                return ResourceManager.GetString("ReviewHotspotService_AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewing hotspot was not permitted due to: {0}..
        /// </summary>
        public static string ReviewHotspotService_NotPermitted {
            get {
                return ResourceManager.GetString("ReviewHotspotService_NotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code has been reviewed and does pose a risk. A fix is required..
        /// </summary>
        public static string ReviewHotspotWindow_AcknowledgeContent {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_AcknowledgeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged.
        /// </summary>
        public static string ReviewHotspotWindow_AcknowledgeTitle {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_AcknowledgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ReviewHotspotWindow_CancelButton {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hotspot can not be reviewed due to the following error: {0}
        ///Please check the logs for more details..
        /// </summary>
        public static string ReviewHotspotWindow_CheckReviewPermittedFailureMessage {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_CheckReviewPermittedFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Hotspot Failure.
        /// </summary>
        public static string ReviewHotspotWindow_FailureTitle {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_FailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code has been reviewed and modified to follow the recommended secure coding practices..
        /// </summary>
        public static string ReviewHotspotWindow_FixedContent {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_FixedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string ReviewHotspotWindow_FixedTitle {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_FixedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reviewing the hotspot. The status has not been changed.
        ///Please check the logs for more details..
        /// </summary>
        public static string ReviewHotspotWindow_ReviewFailureMessage {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_ReviewFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code has been reviewed and does not pose a risk. It does not need to be modified..
        /// </summary>
        public static string ReviewHotspotWindow_SafeContent {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_SafeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.
        /// </summary>
        public static string ReviewHotspotWindow_SafeTitle {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_SafeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ReviewHotspotWindow_SubmitButton {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Security Hotspot Status on SonarQube (Server, Cloud).
        /// </summary>
        public static string ReviewHotspotWindow_Title {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This security hotspot needs to be reviewed to assess whether the code poses a risk..
        /// </summary>
        public static string ReviewHotspotWindow_ToReviewContent {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_ToReviewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Review.
        /// </summary>
        public static string ReviewHotspotWindow_ToReviewTitle {
            get {
                return ResourceManager.GetString("ReviewHotspotWindow_ToReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing security package....
        /// </summary>
        public static string StartedPackageInitialization {
            get {
                return ResourceManager.GetString("StartedPackageInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube Taint Vulnerabilities.
        /// </summary>
        public static string TaintToolWindowCaption {
            get {
                return ResourceManager.GetString("TaintToolWindowCaption", resourceCulture);
            }
        }
    }
}
