//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarLint.VisualStudio.Integration.TeamExplorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarLint.VisualStudio.Integration.TeamExplorer.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect....
        /// </summary>
        public static string ConnectLinkText {
            get {
                return ResourceManager.GetString("ConnectLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info....
        /// </summary>
        public static string MoreInfoLinkText {
            get {
                return ResourceManager.GetString("MoreInfoLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarSource and Microsoft.
        /// </summary>
        public static string ProductAuthors {
            get {
                return ResourceManager.GetString("ProductAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a SonarQube project and bind it to the current solution..
        /// </summary>
        public static string SelectProjectInstruction {
            get {
                return ResourceManager.GetString("SelectProjectInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no projects).
        /// </summary>
        public static string ServerNoProjectsInlineText {
            get {
                return ResourceManager.GetString("ServerNoProjectsInlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube is an open source platform to manage code quality. Connect your solution to an existing SonarQube Server to get the same issues in Visual Studio and in your SonarQube server..
        /// </summary>
        public static string SonarQubeDescription {
            get {
                return ResourceManager.GetString("SonarQubeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube.
        /// </summary>
        public static string SonarQubeName {
            get {
                return ResourceManager.GetString("SonarQubeName", resourceCulture);
            }
        }
    }
}
