// <copyright file="SqmCommandFacade.cs" company="SonarSource SA and Microsoft Corporation">
//   Copyright (c) SonarSource SA and Microsoft Corporation.  All rights reserved.
//   Licensed under the MIT License. See License.txt in the project root for license information.
// </copyright>

// <auto-generated>                                                          
// This code was generated using text template tool.                         
//                                                                           
// Changes to this file may cause incorrect behavior and will be lost if     
// the code is regenerated.                                                  
// </auto-generated>                                                         
//                                                                           
// This file contains SQM trace logging methods.

using EnvDTE;
using System;
using System.Globalization;
using Microsoft.VisualStudio;

namespace SonarLint.VisualStudio.Integration
{
    /// <summary>
    /// Implementation of the facade to raise SQM commands.
    /// </summary>
    /// <remarks>Note that this facade only raises the commands via the DTE. There also needs to be
    /// code to handle the commands.
    /// </remarks>
    internal static partial class SonarLintSqmFacade
    {
        #region Fields
        private static readonly Guid CommandSetIdentifier = new Guid("{DB0701CC-1E44-41F7-97D6-29B160A70BCB}");
        private static IServiceProvider serviceProvider;
        private static DTE dte;
        #endregion

        /// <summary>
        /// Initialize the SQM facade.
        /// </summary>
        /// <remarks>This method can be called multiple times, but any calls after the first successful call will be no-ops.</remarks>
        public static void Initialize(IServiceProvider provider)
        {
            if (provider == null)
            {
                throw new ArgumentNullException(nameof(provider));
            }
            
            serviceProvider = provider;

            DEBUG_SetSqmInitialized();

            if (dte == null)
            {
                dte = serviceProvider.GetService(typeof(DTE)) as DTE;
            }
        }

        /// <summary>
        /// Internal method to reset the facade to its uninitialized state.
        /// </summary>
        /// <remarks>This methods only exists for testing i.e. so unit tests can reset the facade
        /// to try out different test cases.</remarks>
        internal static void Reset()
        {
            DEBUG_Reset();
            dte = null;
        }

        /// <summary>
        /// SQM command for BoundSolutionDetected.
        /// </summary>
        public static void BoundSolutionDetected()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.BoundSolutionDetectedCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("BoundSolutionDetected");
        }

        /// <summary>
        /// SQM command for ConnectCommand.
        /// </summary>
        public static void ConnectCommand()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.ConnectCommandCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("ConnectCommand");
        }

        /// <summary>
        /// SQM command for BindCommand.
        /// </summary>
        public static void BindCommand()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.BindCommandCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("BindCommand");
        }

        /// <summary>
        /// SQM command for BrowseToUrlCommand.
        /// </summary>
        public static void BrowseToUrlCommand()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.BrowseToUrlCommandCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("BrowseToUrlCommand");
        }

        /// <summary>
        /// SQM command for BrowseToProjectDashboardCommand.
        /// </summary>
        public static void BrowseToProjectDashboardCommand()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.BrowseToProjectDashboardCommandCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("BrowseToProjectDashboardCommand");
        }

        /// <summary>
        /// SQM command for RefreshCommand.
        /// </summary>
        public static void RefreshCommand()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.RefreshCommandCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("RefreshCommand");
        }

        /// <summary>
        /// SQM command for DisconnectCommand.
        /// </summary>
        public static void DisconnectCommand()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.DisconnectCommandCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("DisconnectCommand");
        }

        /// <summary>
        /// SQM command for ToggleShowAllProjectsCommand.
        /// </summary>
        public static void ToggleShowAllProjectsCommand()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.ToggleShowAllProjectsCommandCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("ToggleShowAllProjectsCommand");
        }

        /// <summary>
        /// SQM command for FixConflictsCommand.
        /// </summary>
        public static void FixConflictsCommand()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.FixConflictsCommandCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("FixConflictsCommand");
        }

        /// <summary>
        /// SQM command for FixConflictsShow.
        /// </summary>
        public static void FixConflictsShow()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.FixConflictsShowCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("FixConflictsShow");
        }

        /// <summary>
        /// SQM command for ErrorListInfoBarShow.
        /// </summary>
        public static void ErrorListInfoBarShow()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.ErrorListInfoBarShowCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("ErrorListInfoBarShow");
        }

        /// <summary>
        /// SQM command for ErrorListInfoBarUpdateCommand.
        /// </summary>
        public static void ErrorListInfoBarUpdateCommand()
        {
            RunCommand(CommandSetIdentifier, (int)SonarLintSqmCommandIds.ErrorListInfoBarUpdateCommandCommandId);
            DEBUG_LogSqmCommandsToOutputWindow("ErrorListInfoBarUpdateCommand");
        }

        #region Private methods
        private static void RunCommand(Guid commandGroup, int commandId)
        {
            DEBUG_CheckSqmInitialized();

            object customIn = null;
            object customOut = null;

            try
            {
                if (dte != null)
                {
                    // We have to use the DTE way of raising the command to get Sqm data recording for free. 
                    // NOTE: Doing a Exec on the SUIHostCommandDispatcher is downlevel operation that will not
                    // perform any Sqm logging, which is not what we want.
                    dte.Commands.Raise(commandGroup.ToString("B").ToUpper(CultureInfo.InvariantCulture), commandId, ref customIn, ref customOut);
                }
            }
            catch (Exception ex)
            {
                if (ErrorHandler.IsCriticalException(ex))
                {
                    throw;
                }

                // We don't want to bubble any non-critical exceptions while logging SQM data

                // An error here probably means that a handler for the command has 
                // not been found - check that the handler code exists and is correctly registered.
                // NOTE: make sure you ran devenv /setup
                LogSqmException(ex);
                System.Diagnostics.Debug.Fail("Sqm logging failed: " + ex.ToString());
            }
        }

        /// <summary>
        /// Partial method called if an exception occurs when raising the SQM command.
        /// </summary>
        /// <remarks>This is an extension point to the text template to allow customized error processing.</remarks>
        static partial void LogSqmException(Exception ex);

        #endregion

        #region Debug-only methods

        private static bool initialized;

        [System.Diagnostics.Conditional("DEBUG")]
        private static void DEBUG_CheckSqmInitialized()
        {
            System.Diagnostics.Debug.Assert(initialized, "Attempting to use the SonarLint SQM facade before it has been initialized.");
        }

        [System.Diagnostics.Conditional("DEBUG")]
        private static void DEBUG_SetSqmInitialized()
        {
            initialized = true;
        }

        [System.Diagnostics.Conditional("DEBUG")]
        private static void DEBUG_Reset()
        {
            initialized = false;
        }

        /// <summary>
        /// Log to output window to enable manual verification of the sequence of SQM commands that are fired.
        /// </summary>
        [System.Diagnostics.Conditional("DEBUG")]
        private static void DEBUG_LogSqmCommandsToOutputWindow(string command)
        {
            VsShellUtils.WriteToSonarLintOutputPane(serviceProvider, "[DEBUG SonarLintSqmFacade] {0}", command);
        }

        #endregion

    }
}
