//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarLint.VisualStudio.Integration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarLint.VisualStudio.Integration.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound project: {0}.
        /// </summary>
        public static string AutomationProjectBoundDescription {
            get {
                return ResourceManager.GetString("AutomationProjectBoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube server: {0}.
        /// </summary>
        public static string AutomationServerDescription {
            get {
                return ResourceManager.GetString("AutomationServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube server: {0}. This server has no projects..
        /// </summary>
        public static string AutomationServerNoProjectsDescription {
            get {
                return ResourceManager.GetString("AutomationServerNoProjectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind.
        /// </summary>
        public static string BindButtonText {
            get {
                return ResourceManager.GetString("BindButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language for project &apos;{0}&apos; is not matching any of the available quality profile&apos;s languages.
        /// </summary>
        public static string BindingProjectLanguageNotMatchingAnyQualityProfileLanguage {
            get {
                return ResourceManager.GetString("BindingProjectLanguageNotMatchingAnyQualityProfileLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding projects.
        /// </summary>
        public static string BindingProjectsDisplayMessage {
            get {
                return ResourceManager.GetString("BindingProjectsDisplayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding solution to SonarQube project: {0}.
        /// </summary>
        public static string BindingSolutionPrefixMessageFormat {
            get {
                return ResourceManager.GetString("BindingSolutionPrefixMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound project with key &apos;{0}&apos; was not found on the connected server. Select a new SonarQube project and bind to it..
        /// </summary>
        public static string BoundProjectNotFound {
            get {
                return ResourceManager.GetString("BoundProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse the server in your web browser..
        /// </summary>
        public static string BrowserServerMenuItemTooltip {
            get {
                return ResourceManager.GetString("BrowserServerMenuItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseServerMenuItemDisplayText {
            get {
                return ResourceManager.GetString("BrowseServerMenuItemDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca_ncel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLinkText {
            get {
                return ResourceManager.GetString("CancelLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SonarQube server plugin has a malformed version and cannot be compared. Version was &apos;{0}&apos;..
        /// </summary>
        public static string CannotCompareVersionStrings {
            get {
                return ResourceManager.GetString("CannotCompareVersionStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download the quality profile for language {0}.
        /// </summary>
        public static string CannotDownloadQualityProfileForLanguage {
            get {
                return ResourceManager.GetString("CannotDownloadQualityProfileForLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing rules (or Action set to None): .
        /// </summary>
        public static string ConflictDetailMissingRules {
            get {
                return ResourceManager.GetString("ConflictDetailMissingRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleSet &apos;{0}&apos; has:.
        /// </summary>
        public static string ConflictDetailRuleSetInfo {
            get {
                return ResourceManager.GetString("ConflictDetailRuleSetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule &apos;{0}&apos; action is {1}, instead of {2}..
        /// </summary>
        public static string ConflictDetailWeakenedRulesDetail {
            get {
                return ResourceManager.GetString("ConflictDetailWeakenedRulesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weakened rules:.
        /// </summary>
        public static string ConflictDetailWeakenedRulesTitle {
            get {
                return ResourceManager.GetString("ConflictDetailWeakenedRulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleSet conflicts resolution summary for project &apos;{0}&apos;, configuration(s): {1}.
        /// </summary>
        public static string ConflictFixHeader {
            get {
                return ResourceManager.GetString("ConflictFixHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleSet imports were reset for: &apos;{0}&apos;..
        /// </summary>
        public static string ConflictFixResetInclude {
            get {
                return ResourceManager.GetString("ConflictFixResetInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting rules were removed from &apos;{0}&apos;:.
        /// </summary>
        public static string ConflictFixRulesDeleted {
            get {
                return ResourceManager.GetString("ConflictFixRulesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleSet &apos;{0}&apos; cannot be analyzed against &apos;{1}&apos; due to error: {2}. .
        /// </summary>
        public static string ConflictsManagerFailedInFindConflicts {
            get {
                return ResourceManager.GetString("ConflictsManagerFailedInFindConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarLint conflicts manager warning: {0}.
        /// </summary>
        public static string ConflictsManagerWarningMessage {
            get {
                return ResourceManager.GetString("ConflictsManagerWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleSet conflicts detected for project &apos;{0}&apos;, configuration(s): {1}.
        /// </summary>
        public static string ConflictsSummaryHeader {
            get {
                return ResourceManager.GetString("ConflictsSummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Connect.
        /// </summary>
        public static string ConnectButtonText {
            get {
                return ResourceManager.GetString("ConnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a SonarQube Server.
        /// </summary>
        public static string ConnectDialogTitle {
            get {
                return ResourceManager.GetString("ConnectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        public static string ConnectingToSever {
            get {
                return ResourceManager.GetString("ConnectingToSever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to SonarQube server: {0}.
        /// </summary>
        public static string ConnectingToSonarQubePrefixMessageFormat {
            get {
                return ResourceManager.GetString("ConnectingToSonarQubePrefixMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the SonarQube server. Make sure you provided the correct connection information, including your sign-in credentials, and [try again]().
        ///See more information in the output window (SonarLint)..
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string ConnectionResultCancellation {
            get {
                return ResourceManager.GetString("ConnectionResultCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string ConnectionResultFailure {
            get {
                return ResourceManager.GetString("ConnectionResultFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string ConnectionResultSuccess {
            get {
                return ResourceManager.GetString("ConnectionResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving organizations.
        /// </summary>
        public static string ConnectionStepRetrievingOrganizations {
            get {
                return ResourceManager.GetString("ConnectionStepRetrievingOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving projects.
        /// </summary>
        public static string ConnectionStepRetrievingProjects {
            get {
                return ResourceManager.GetString("ConnectionStepRetrievingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating credentials.
        /// </summary>
        public static string ConnectionStepValidatinCredentials {
            get {
                return ResourceManager.GetString("ConnectionStepValidatinCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect....
        /// </summary>
        public static string ConnectLinkText {
            get {
                return ResourceManager.GetString("ConnectLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ConnectSectionTitle {
            get {
                return ResourceManager.GetString("ConnectSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: could not find CodeAnalysisRuleSet for project &apos;{0}&apos;.
        /// </summary>
        public static string CouldNotFindCodeAnalysisRuleSetPropertyOnProject {
            get {
                return ResourceManager.GetString("CouldNotFindCodeAnalysisRuleSetPropertyOnProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        public static string CSharpLanguageName {
            get {
                return ResourceManager.GetString("CSharpLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting server plugins.
        /// </summary>
        public static string DetectingSonarQubePlugins {
            get {
                return ResourceManager.GetString("DetectingSonarQubePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string DisconnectCommandDisplayText {
            get {
                return ResourceManager.GetString("DisconnectCommandDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from SonarQube project.
        /// </summary>
        public static string DisconnectCommandTooltip {
            get {
                return ResourceManager.GetString("DisconnectCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {0}.
        /// </summary>
        public static string DiscoveredIncludedOrExcludedProjectFormat {
            get {
                return ResourceManager.GetString("DiscoveredIncludedOrExcludedProjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded projects:.
        /// </summary>
        public static string DiscoveringSolutionExcludedProjectsHeader {
            get {
                return ResourceManager.GetString("DiscoveringSolutionExcludedProjectsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included projects:.
        /// </summary>
        public static string DiscoveringSolutionIncludedProjectsHeader {
            get {
                return ResourceManager.GetString("DiscoveringSolutionIncludedProjectsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering solution projects.
        /// </summary>
        public static string DiscoveringSolutionProjectsProgressMessage {
            get {
                return ResourceManager.GetString("DiscoveringSolutionProjectsProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download quality profile(s):.
        /// </summary>
        public static string DownloadingQualityProfileProgressMessage {
            get {
                return ResourceManager.GetString("DownloadingQualityProfileProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading server settings..
        /// </summary>
        public static string DownloadingServerSettingsProgessMessage {
            get {
                return ResourceManager.GetString("DownloadingServerSettingsProgessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing NuGet package &apos;{0}&apos; for project &apos;{1}&apos;.
        /// </summary>
        public static string EnsuringNugetPackagesProgressMessage {
            get {
                return ResourceManager.GetString("EnsuringNugetPackagesProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insecure schemes must be a subset of supported schemes.
        /// </summary>
        public static string ExceptionInsecureSchemesIsNotSubset {
            get {
                return ResourceManager.GetString("ExceptionInsecureSchemesIsNotSubset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target URI must be an absolute URI.
        /// </summary>
        public static string ExpectedAbsoluteUris {
            get {
                return ResourceManager.GetString("ExpectedAbsoluteUris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected RuleSet file &apos;{0}&apos; could not be resolved or the file does not exist. Cannot search conflicts for one or more project configuration of project &apos;{1}&apos;. Please rebind to the relevant SonarQube project from TeamExplorer window..
        /// </summary>
        public static string ExpectedRuleSetNotFound {
            get {
                return ResourceManager.GetString("ExpectedRuleSetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install NuGet package &apos;{0}&apos; for project &apos;{1}&apos;. Message: {2}.
        /// </summary>
        public static string FailedDuringNuGetPackageInstall {
            get {
                return ResourceManager.GetString("FailedDuringNuGetPackageInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete credentials for {0}..
        /// </summary>
        public static string FailedToDeleteCredentials {
            get {
                return ResourceManager.GetString("FailedToDeleteCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading file: &apos;{0}&apos;. Please rebind solution to create a new configuration file..
        /// </summary>
        public static string FailedToDeserializeSQCOnfiguration {
            get {
                return ResourceManager.GetString("FailedToDeserializeSQCOnfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to bind the solution to SonarQube project, [try again]().
        ///See more information in the output window (SonarLint)..
        /// </summary>
        public static string FailedToToBindSolution {
            get {
                return ResourceManager.GetString("FailedToToBindSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unpack additional files required for analyzers.
        /// </summary>
        public static string FailedToUnpackAdditionalFiles {
            get {
                return ResourceManager.GetString("FailedToUnpackAdditionalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change the exclusion options via the SonarLint project-level context menu i.e. Solution Explorer -&gt; Select project(s).
        /// </summary>
        public static string FilteredOutProjectFromBindingEnding {
            get {
                return ResourceManager.GetString("FilteredOutProjectFromBindingEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following projects are either not currently supported, excluded according to server specifications, or have been explicitly marked as excluded:.
        /// </summary>
        public static string FilteredOutProjectFromBindingHeader {
            get {
                return ResourceManager.GetString("FilteredOutProjectFromBindingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all NuGet packages were installed. Please see output above for more information..
        /// </summary>
        public static string FinishedSolutionBindingWorkflowNotAllPackagesInstalled {
            get {
                return ResourceManager.GetString("FinishedSolutionBindingWorkflowNotAllPackagesInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed successfully.
        /// </summary>
        public static string FinishedSolutionBindingWorkflowSuccessful {
            get {
                return ResourceManager.GetString("FinishedSolutionBindingWorkflowSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Unbound Projects.
        /// </summary>
        public static string HideUnboundProjectsCommandText {
            get {
                return ResourceManager.GetString("HideUnboundProjectsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different CodeAnalysisRuleSetDirectories value &apos;{0}&apos; for RuleSet &apos;{1}&apos;. Using value &apos;{2}&apos;..
        /// </summary>
        public static string InconsistentRuleSetDirectoriesWarning {
            get {
                return ResourceManager.GetString("InconsistentRuleSetDirectoriesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL you entered is not secure. Use HTTPS connections to protect sensitive information..
        /// </summary>
        public static string InsecureProtocolWarning {
            get {
                return ResourceManager.GetString("InsecureProtocolWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon (&quot;:&quot;) is not a permitted character..
        /// </summary>
        public static string InvalidCharacterColon {
            get {
                return ResourceManager.GetString("InvalidCharacterColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid URL.
        /// </summary>
        public static string InvalidServerUriFormat {
            get {
                return ResourceManager.GetString("InvalidServerUriFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test project regular expression pattern &apos;{0}&apos; is invalid. The default will be used instead. Please check your server settings..
        /// </summary>
        public static string InvalidTestProjectRegexPattern {
            get {
                return ResourceManager.GetString("InvalidTestProjectRegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: &apos;{0}&apos;, Minimum version: &apos;{1}&apos;.
        /// </summary>
        public static string MinimumSupportedSonarQubePlugin {
            get {
                return ResourceManager.GetString("MinimumSupportedSonarQubePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not acquire service: {0}.
        /// </summary>
        public static string MissingService {
            get {
                return ResourceManager.GetString("MissingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info....
        /// </summary>
        public static string MoreInfoLinkText {
            get {
                return ResourceManager.GetString("MoreInfoLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with Sonar{0}, information about the associated NuGet package was not returned.
        /// </summary>
        public static string NoNuGetPackageForQualityProfile {
            get {
                return ResourceManager.GetString("NoNuGetPackageForQualityProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None (for selected SonarQube project&apos;s quality profile).
        /// </summary>
        public static string NoProjectsApplicableForBinding {
            get {
                return ResourceManager.GetString("NoProjectsApplicableForBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None (for selected SonarQube project&apos;s quality profile).
        /// </summary>
        public static string NoProjectsExcludedFromBinding {
            get {
                return ResourceManager.GetString("NoProjectsExcludedFromBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no active rules on the selected Quality Profile &apos;{0}&apos; for Language {1} (rules from the SonarAnalyzer repository). Connected mode requires at least one active rule.
        ///   Note that third party rules are excluded from SonarLint.
        /// </summary>
        public static string NoSonarAnalyzerActiveRulesForQualityProfile {
            get {
                return ResourceManager.GetString("NoSonarAnalyzerActiveRulesForQualityProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field can not be empty.
        /// </summary>
        public static string NotEmptyValidatorRequiredField {
            get {
                return ResourceManager.GetString("NotEmptyValidatorRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This SonarQube server only supported plugin language ({0}) does not match any of this solution projects&apos; languages..
        /// </summary>
        public static string OnlySupportedPluginHasNoProjectInSolution {
            get {
                return ResourceManager.GetString("OnlySupportedPluginHasNoProjectInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An absolute file path was expected..
        /// </summary>
        public static string PathHelperAbsolutePathExpected {
            get {
                return ResourceManager.GetString("PathHelperAbsolutePathExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarSource and Microsoft.
        /// </summary>
        public static string ProductAuthors {
            get {
                return ResourceManager.GetString("ProductAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get the IVsHierarchy/IVsBuildPropertyStorage for the given project is IVsBuildPropertyStorage for the given EnvDTE.Project.
        /// </summary>
        public static string ProjectFilterDteProjectFailedToGetIVs {
            get {
                return ResourceManager.GetString("ProjectFilterDteProjectFailedToGetIVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key: {0}.
        /// </summary>
        public static string ProjectToolTipKeyFormat {
            get {
                return ResourceManager.GetString("ProjectToolTipKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Bound).
        /// </summary>
        public static string ProjectToolTipProjectNameFormat {
            get {
                return ResourceManager.GetString("ProjectToolTipProjectNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download quality profile. Name: &apos;{0}&apos;, Key: &apos;{1}&apos;, Language: &apos;{2}&apos;.
        /// </summary>
        public static string QualityProfileDownloadFailedMessageFormat {
            get {
                return ResourceManager.GetString("QualityProfileDownloadFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded quality profile. Name: &apos;{0}&apos;, Key: &apos;{1}&apos;, Language: &apos;{2}&apos;.
        /// </summary>
        public static string QualityProfileDownloadSuccessfulMessageFormat {
            get {
                return ResourceManager.GetString("QualityProfileDownloadSuccessfulMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshCommandDisplayText {
            get {
                return ResourceManager.GetString("RefreshCommandDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will refetch the SonarQube projects from the server using the existing credentials.
        /// </summary>
        public static string RefreshCommandTooltip {
            get {
                return ResourceManager.GetString("RefreshCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applied ruleset is weakening the SonarQube quality profile in one or more projects. See output window (SonarLint) for more details. [Click here]() to fix automatically..
        /// </summary>
        public static string RuleSetConflictsDetected {
            get {
                return ResourceManager.GetString("RuleSetConflictsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule set generated from SonarQube.
        /// </summary>
        public static string RuleSetDescription {
            get {
                return ResourceManager.GetString("RuleSetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating project rule sets.
        /// </summary>
        public static string RuleSetGenerationProgressMessage {
            get {
                return ResourceManager.GetString("RuleSetGenerationProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a SonarQube project and bind it to the current solution..
        /// </summary>
        public static string SelectSonarQubeProjectInstruction {
            get {
                return ResourceManager.GetString("SelectSonarQubeProjectInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified SonarQube server does not have the minimum required version of any of the supported plugins (C#, VB.Net). .
        /// </summary>
        public static string ServerHasNoSupportedPluginVersion {
            get {
                return ResourceManager.GetString("ServerHasNoSupportedPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no projects).
        /// </summary>
        public static string ServerNoProjectsInlineText {
            get {
                return ResourceManager.GetString("ServerNoProjectsInlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server has no available projects with which to bind to. Please create at least one project and then refresh this connection..
        /// </summary>
        public static string ServerNoProjectsToolTipText {
            get {
                return ResourceManager.GetString("ServerNoProjectsToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet analyzer packages may be downloaded and installed automatically when you bind to a SonarQube project.
        ///[Don&apos;t warn me again]().
        /// </summary>
        public static string ServerNuGetTrustWarningMessage {
            get {
                return ResourceManager.GetString("ServerNuGetTrustWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Projects.
        /// </summary>
        public static string ShowAllProjectsCommandText {
            get {
                return ResourceManager.GetString("ShowAllProjectsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a warning about automatically downloading NuGet packages when establishing a SonarQube server connection..
        /// </summary>
        public static string ShowServerNuGetTrustWarningSettingDescription {
            get {
                return ResourceManager.GetString("ShowServerNuGetTrustWarningSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show NuGet package warnings.
        /// </summary>
        public static string ShowServerNuGetTrustWarningSettingName {
            get {
                return ResourceManager.GetString("ShowServerNuGetTrustWarningSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution contains no supported project language (C#, VB.Net). Please create at least one project of the supported language and then try to reconnect..
        /// </summary>
        public static string SolutionContainsNoSupportedProject {
            get {
                return ResourceManager.GetString("SolutionContainsNoSupportedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation requires an open solution..
        /// </summary>
        public static string SolutionIsClosed {
            get {
                return ResourceManager.GetString("SolutionIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind or sync if there are unsaved changes. Operation canceled..
        /// </summary>
        public static string SolutionSaveCancelledBindAborted {
            get {
                return ResourceManager.GetString("SolutionSaveCancelledBindAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for unbound projects..
        /// </summary>
        public static string SonarLintCheckingForUnboundProjects {
            get {
                return ResourceManager.GetString("SonarLintCheckingForUnboundProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to attach info bar to error list tool window..
        /// </summary>
        public static string SonarLintFailedToAttachInfoBarToErrorList {
            get {
                return ResourceManager.GetString("SonarLintFailedToAttachInfoBarToErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unbound projects were found ({1})..
        /// </summary>
        public static string SonarLintFoundUnboundProjects {
            get {
                return ResourceManager.GetString("SonarLintFoundUnboundProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarLint can now tell you when the quality profile in SonarQube project is updated. Press Update to enable this feature now..
        /// </summary>
        public static string SonarLintInfoBarOldBindingFile {
            get {
                return ResourceManager.GetString("SonarLintInfoBarOldBindingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more rule sets are out of date or not linked to the SonarQube quality profile rule set. See output window (SonarLint) for affected projects..
        /// </summary>
        public static string SonarLintInfoBarUnboundProjectsMessage {
            get {
                return ResourceManager.GetString("SonarLintInfoBarUnboundProjectsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current solution is not bound to the expected SonarQube project, aborting..
        /// </summary>
        public static string SonarLintInfoBarUpdateCommandInvalidSolutionBindings {
            get {
                return ResourceManager.GetString("SonarLintInfoBarUpdateCommandInvalidSolutionBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update the binding because the command is not currently available. Please try again and ensure that the solution is not building or currently being debugged..
        /// </summary>
        public static string SonarLintInfoBarUpdateCommandIsBusyRetry {
            get {
                return ResourceManager.GetString("SonarLintInfoBarUpdateCommandIsBusyRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SonarQube Team Explorer page was closed and we cannot proceed with the update. Please try again..
        /// </summary>
        public static string SonarLintInfoBarUpdateCommandRetryNoActiveSection {
            get {
                return ResourceManager.GetString("SonarLintInfoBarUpdateCommandRetryNoActiveSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string SonarLintInfoBarUpdateCommandText {
            get {
                return ResourceManager.GetString("SonarLintInfoBarUpdateCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No unbound projects were found..
        /// </summary>
        public static string SonarLintNoUnboundProjectWereFound {
            get {
                return ResourceManager.GetString("SonarLintNoUnboundProjectWereFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarLint.
        /// </summary>
        public static string SonarLintOutputPaneTitle {
            get {
                return ResourceManager.GetString("SonarLintOutputPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if SonarQube Quality profile has changed..
        /// </summary>
        public static string SonarLintProfileCheck {
            get {
                return ResourceManager.GetString("SonarLintProfileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SonarQube project is using a different Quality Profile. Update is required..
        /// </summary>
        public static string SonarLintProfileCheckDifferentProfile {
            get {
                return ResourceManager.GetString("SonarLintProfileCheckDifferentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected failure getting quality profile information. Automatic quality profile update will not be performed..
        /// </summary>
        public static string SonarLintProfileCheckFailed {
            get {
                return ResourceManager.GetString("SonarLintProfileCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding information is out of date. Update is required..
        /// </summary>
        public static string SonarLintProfileCheckNoProfiles {
            get {
                return ResourceManager.GetString("SonarLintProfileCheckNoProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Quality Profile for the SonarQube project has changed. Update is required..
        /// </summary>
        public static string SonarLintProfileCheckProfileUpdated {
            get {
                return ResourceManager.GetString("SonarLintProfileCheckProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Profile is up-to-date..
        /// </summary>
        public static string SonarLintProfileCheckQualityProfileIsUpToDate {
            get {
                return ResourceManager.GetString("SonarLintProfileCheckQualityProfileIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution has changed and now requires additional Quality Profiles to be included. Update is required..
        /// </summary>
        public static string SonarLintProfileCheckSolutionRequiresMoreProfiles {
            get {
                return ResourceManager.GetString("SonarLintProfileCheckSolutionRequiresMoreProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube is an open source platform to manage code quality. Connect your solution to an existing SonarQube Server to get the same issues in Visual Studio and in your SonarQube server..
        /// </summary>
        public static string SonarQubeDescription {
            get {
                return ResourceManager.GetString("SonarQubeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube.
        /// </summary>
        public static string SonarQubeName {
            get {
                return ResourceManager.GetString("SonarQubeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning failed calling &apos;{0}&apos; (http error code={1}). Some of the functionality will be reduced..
        /// </summary>
        public static string SonarQubeOptionalServiceFailed {
            get {
                return ResourceManager.GetString("SonarQubeOptionalServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}profiles/show?key={1}.
        /// </summary>
        public static string SonarQubeQualityProfilePageUrlFormat {
            get {
                return ResourceManager.GetString("SonarQubeQualityProfilePageUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube request failed: {0} {1}.
        /// </summary>
        public static string SonarQubeRequestFailed {
            get {
                return ResourceManager.GetString("SonarQubeRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube request timed out or was canceled.
        /// </summary>
        public static string SonarQubeRequestTimeoutOrCancelled {
            get {
                return ResourceManager.GetString("SonarQubeRequestTimeoutOrCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube - {0} {1}.
        /// </summary>
        public static string SonarQubeRuleSetNameFormat {
            get {
                return ResourceManager.GetString("SonarQubeRuleSetNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube server:.
        /// </summary>
        public static string SonarQubeServerLabel {
            get {
                return ResourceManager.GetString("SonarQubeServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string StartedSolutionBindingWorkflow {
            get {
                return ResourceManager.GetString("StartedSolutionBindingWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    {0}.
        /// </summary>
        public static string SubTextPaddingFormat {
            get {
                return ResourceManager.GetString("SubTextPaddingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed NuGet package &apos;{0}&apos; for project &apos;{1}&apos;.
        /// </summary>
        public static string SuccessfullyInstalledNugetPackageForProject {
            get {
                return ResourceManager.GetString("SuccessfullyInstalledNugetPackageForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered a supported plugin: {0}.
        /// </summary>
        public static string SupportedPluginFoundMessage {
            get {
                return ResourceManager.GetString("SupportedPluginFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string SyncButtonText {
            get {
                return ResourceManager.GetString("SyncButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube.
        /// </summary>
        public static string TeamExplorerPageTitle {
            get {
                return ResourceManager.GetString("TeamExplorerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle visibility of unbound projects for this server..
        /// </summary>
        public static string ToggleShowAllProjectsCommandTooltip {
            get {
                return ResourceManager.GetString("ToggleShowAllProjectsCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Unexpected error: {1}. You can help us improve by reporting this bug at {2}..
        /// </summary>
        public static string UnexpectedErrorMessageFormat {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token type encountered.
        /// </summary>
        public static string UnexpectedTokenType {
            get {
                return ResourceManager.GetString("UnexpectedTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error during workflow execution: {0}..
        /// </summary>
        public static string UnexpectedWorkflowError {
            get {
                return ResourceManager.GetString("UnexpectedWorkflowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownLanguageName {
            get {
                return ResourceManager.GetString("UnknownLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking additional file: {0}.
        /// </summary>
        public static string UnpackingAdditionalFile {
            get {
                return ResourceManager.GetString("UnpackingAdditionalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered an unsupported plugin: {0}.
        /// </summary>
        public static string UnsupportedPluginFoundMessage {
            get {
                return ResourceManager.GetString("UnsupportedPluginFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Token:.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a password is specified, a username must also be specified..
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB.NET.
        /// </summary>
        public static string VBNetLanguageName {
            get {
                return ResourceManager.GetString("VBNetLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in SonarQube.
        /// </summary>
        public static string ViewInSonarQubeMenuItemDisplayText {
            get {
                return ResourceManager.GetString("ViewInSonarQubeMenuItemDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the dashboard for this project in SonarQube using your web browser..
        /// </summary>
        public static string ViewInSonarQubeMenuItemTooltip {
            get {
                return ResourceManager.GetString("ViewInSonarQubeMenuItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string WarningsSettingsCategory {
            get {
                return ResourceManager.GetString("WarningsSettingsCategory", resourceCulture);
            }
        }
    }
}
