//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarLint.VisualStudio.Integration.Vsix.CFamily {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CFamilyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CFamilyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyStrings", typeof(CFamilyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File configuration &apos;{0}&apos; defines &apos;{1}&apos;. Value: &apos;{2}&apos;.
        /// </summary>
        internal static string CompilationDatabaseEntryGenerator_FilePropertyDefined {
            get {
                return ResourceManager.GetString("CompilationDatabaseEntryGenerator_FilePropertyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File configuration &apos;{0}&apos; overrides &apos;{1}&apos;. Old value: &apos;{2}&apos;, new value: &apos;{3}&apos;.
        /// </summary>
        internal static string CompilationDatabaseEntryGenerator_FilePropertyOverridesEnvironmentVariable {
            get {
                return ResourceManager.GetString("CompilationDatabaseEntryGenerator_FilePropertyOverridesEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is not a VCX file, ignoring....
        /// </summary>
        internal static string CompilationDatabaseEntryGenerator_NotAVcxFile {
            get {
                return ResourceManager.GetString("CompilationDatabaseEntryGenerator_NotAVcxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CFamily Analysis] Error retrieving VCX configuration. File: {0}, Error: {1}.
        /// </summary>
        internal static string ERROR_CreatingConfig {
            get {
                return ResourceManager.GetString("ERROR_CreatingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CFamily Analysis] Error creating VCX request. File: {0}, Error: {1}.
        /// </summary>
        internal static string ERROR_CreatingVcxRequest {
            get {
                return ResourceManager.GetString("ERROR_CreatingVcxRequest", resourceCulture);
            }
        }
    }
}
