//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarLint.VisualStudio.Integration.Vsix.CFamily {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CFamilyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CFamilyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyStrings", typeof(CFamilyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CFamily Analysis] Error retrieving VCX configuration. File: {0}, Error: {1}.
        /// </summary>
        internal static string ERROR_CreatingConfig {
            get {
                return ResourceManager.GetString("ERROR_CreatingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CFamily Analysis] Error creating VCX request. File: {0}, Error: {1}.
        /// </summary>
        internal static string ERROR_CreatingVcxRequest {
            get {
                return ResourceManager.GetString("ERROR_CreatingVcxRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active document can be analyzed by the CFamily analyzer: {0}.
        /// </summary>
        internal static string ReproCmd_DocumentIsAnalyzable {
            get {
                return ResourceManager.GetString("ReproCmd_DocumentIsAnalyzable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run SonarLint CFamily reproducer - the active document is not analyzable by the CFamily analyzer: {0}.
        /// </summary>
        internal static string ReproCmd_DocumentIsNotAnalyzable {
            get {
                return ResourceManager.GetString("ReproCmd_DocumentIsNotAnalyzable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing the SonarLint CFamily reproducer command:
        ///  Error: {0}.
        /// </summary>
        internal static string ReproCmd_Error_Execute {
            get {
                return ResourceManager.GetString("ReproCmd_Error_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in calculating whether the SonarLint CFamily reproducer command is available:
        ///  Error: {0}.
        /// </summary>
        internal static string ReproCmd_Error_QueryStatus {
            get {
                return ResourceManager.GetString("ReproCmd_Error_QueryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling the SonarLint CFamily reproducer....
        /// </summary>
        internal static string ReproCmd_ExecutingReproducer {
            get {
                return ResourceManager.GetString("ReproCmd_ExecutingReproducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run SonarLint CFamily reproducer - no active document..
        /// </summary>
        internal static string ReproCmd_NoActiveDocument {
            get {
                return ResourceManager.GetString("ReproCmd_NoActiveDocument", resourceCulture);
            }
        }
    }
}
